Description: >

  This is the master template to install the infrastructure for my aws-ramp project. 
  Nested templates are documented in the corresponding files.
    
  Last Modified: 2020-03-03
  Author: Toby Buckley <tobuck@amazon.com>

Parameters:
  BucketName:
    Default: tobuck-cf
    Description: S3 bucket name in which the CloudFormation templates are hosted. Should not
      be the full path to the bucket, just the bucket name itself.
    Type: String
  BucketRegion:
    Default: us-west-2
    Description: The AWS region that the bucket lives in.
    Type: String
  BucketFolder:
    Default: cloudformation
    Description: The folder under the S3 bucket in which the CloudFormation templates live.
    Type: String

Resources:
  ECR:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${BucketName}.s3-${BucketRegion}.amazonaws.com/${BucketFolder}/ecr-repo.yml
  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${BucketName}.s3-${BucketRegion}.amazonaws.com/${BucketFolder}/vpc.yml
      Parameters:
        EnvironmentName: !Ref AWS::StackName
        VpcCIDR: 10.0.0.0/16
        PublicSubnet1CIDR: 10.0.8.0/21
        PublicSubnet2CIDR: 10.0.16.0/21
        PrivateSubnet1CIDR: 10.0.24.0/21
        PrivateSubnet2CIDR: 10.0.32.0/21
  SecurityGroups:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${BucketName}.s3-${BucketRegion}.amazonaws.com/${BucketFolder}/security-groups.yml
      Parameters:
        EnvironmentName: !Ref AWS::StackName
        VPC: !GetAtt VPC.Outputs.VPC
  ALB:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${BucketName}.s3-${BucketRegion}.amazonaws.com/${BucketFolder}/load-balancers.yml
      Parameters:
        EnvironmentName: !Ref AWS::StackName
        VPC: !GetAtt VPC.Outputs.VPC
        Subnets: !GetAtt VPC.Outputs.PublicSubnets
        SecurityGroup: !GetAtt SecurityGroups.Outputs.LoadBalancerSecurityGroup
  ECS:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${BucketName}.s3-${BucketRegion}.amazonaws.com/${BucketFolder}/ecs-cluster.yml
      Parameters:
        EnvironmentName: !Ref AWS::StackName
        InstanceType: t2.micro
        ClusterSize: 4
        VPC: !GetAtt VPC.Outputs.VPC
        SecurityGroup: !GetAtt SecurityGroups.Outputs.ECSHostSecurityGroup
        Subnets: !GetAtt VPC.Outputs.PrivateSubnets
  LifecycleHook:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${BucketName}.s3-${BucketRegion}.amazonaws.com/${BucketFolder}/lifecyclehook.yml
      Parameters:
        Cluster: !GetAtt ECS.Outputs.Cluster
        ECSAutoScalingGroupName: !GetAtt ECS.Outputs.ECSAutoScalingGroupName

Outputs:
  LoadBalancerUrl:
    Description: The URL endpoint for the ALB
    Value: !Join ["", [!GetAtt ALB.Outputs.LoadBalancerUrl, "/"]]
