version: '3'
services:
  web-client:
    build:
      context: ./apps/web-client
      dockerfile: Dockerfile
    image: mobytoby/web-client:latest
    ports:
      - "3000:80"
    links:
      - photo-storage
      - photo-filter
    env_file: 
      - aws.env
    environment:
      DOCKER_COMPOSE: 'true'

  photo-filter:
    build:
      context: ./apps/photo-filter-grayscale
      dockerfile: Dockerfile
    image: mobytoby/photo-filter-grayscale:latest
    ports:
      - "3002:3002"
    env_file: 
      - aws.env

  photo-storage:
    build:
      context: ./apps/photo-storage
      dockerfile: Dockerfile
    image: mobytoby/photo-storage-api:latest
    ports:
      - "3001:3001"
    env_file: 
      - aws.env
